
logging:
  level:
    root: info
    com.springbootbasepackage.controller: debug




server:
  port: 8099
  compression:
    enabled: true
    mime-types:
      - application-json
      - application/xml
      - application/javascript
      - text/html
      - text/xml
      - text/plain
      - text/css
    min-response-size: 2048

spring:
  datasource:
    ufc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dj_second_phase?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: 123456
    filters:
      stat,wall
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: 10
        min-idle: 0
    timeout: 1000






